name: Cypress Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      # 1 – Baixa seu código
      - uses: actions/checkout@v4

      # 2 – Instala a versão do Node usada no projeto
      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      # 3 – Instala dependências (npm ci é mais rápido/seguro em CI)
      - run: npm ci

      # 4 – Roda o Cypress (essa action cuida do download,
      #     permissões, cache, gravação de vídeos/screenshots etc.)
      - name: Cypress run
        uses: cypress-io/github-action@v6
