name: Run Cypress Tests

on:
  push:
    branches:
      - main  # executa quando der push na branch main
  pull_request:
    branches:
      - main  # também executa nos PRs para main

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # ou outra versão que você esteja usando

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests
        run: npx cypress run
